- alias: SEI/USD
  id: 53614f1cb0c031d4af66c04cb9c756234adad0e1cee85303795091499a4084eb
  time_difference: 60
  price_deviation: 1
  confidence_ratio: 1
  early_update:
    time_difference: 30
    price_deviation: 0.5
    confidence_ratio: 0.1
